In [1]:
for i in range(1,6):
    print i

1
2
3
4
5


In [1]:
import numpy as np

In [12]:
a = np.zeros((6,3,3,3))
#X_gen = np.zeros((X_len, height, width*n_len, 1), dtype=np.uint8)

In [13]:
a[5]

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [1]:
b=[10]*5
print(b)

[10, 10, 10, 10, 10]


In [5]:
import numpy as np
np.zeros((3,4,5,2))

array([[[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0

In [12]:
y_gen = [np.zeros((3, 2), dtype=np.uint8) for i in range(4)]

In [13]:
print(y_gen)

[array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8), array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8), array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8), array([[0, 0],
       [0, 0],
       [0, 0]], dtype=uint8)]


In [15]:
a = np.array([2,5,8,9]+[10,10,10])

In [16]:
a

array([ 2,  5,  8,  9, 10, 10, 10])